name: Auto Update Amazon Bestsellers

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run Scraper
      run: |
        python amazon_scraper.py

    - name: Check for Changes
      run: |
        git diff --exit-code || echo "Changes detected."

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add products.js
        git commit -m 'Auto update bestsellers' || echo "No changes to commit"
        git push origin main
