name: Auto Update Amazon Bestsellers

on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 1:00 AM
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install requests beautifulsoup4 openai

    - name: Run Bestseller Script
      env:
        OPENAI_KEY_1: ${{ secrets.OPENAI_KEY_1 }}
        OPENAI_KEY_2: ${{ secrets.OPENAI_KEY_2 }}
        OPENAI_KEY_3: ${{ secrets.OPENAI_KEY_3 }}
        OPENAI_KEY_4: ${{ secrets.OPENAI_KEY_4 }}
        OPENAI_KEY_5: ${{ secrets.OPENAI_KEY_5 }}
      run: |
        python amazon_scraper.py

    - name: Commit Changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m 'Auto update bestsellers' || echo "No changes to commit"
        git pull origin main --rebase
        git push
