name: Auto Generate Blog

on:
  schedule:
    - cron: '30 0 * * *'  # Runs daily at 00:30
  workflow_dispatch:

jobs:
  generate_blog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install requests openai

    - name: Generate Blog
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python generate_blog.py

    - name: Commit Changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add blogs/ blogs.json
        git commit -m 'Auto generate blog'
        git push
